application: nozomi-miraha
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /hello
  script: hello.app
  login: admin

- url: /good-night
  script: goodnight.app
  login: admin

- url: /quote
  script: quote.app
  login: admin

libraries:
- name: webapp2
  version: "2.5.1"
- name: django
  version: "1.4"
