application: nozomi-miraha
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /hello
  script: hello.app
  login: admin

- url: /reply-hello
  script: hello_replier.app
  login: admin

- url: /good-night
  script: goodnight.app
  login: admin

- url: /quote
  script: quote.app
  login: admin

- url: /refollow
  script: refollow.app
  login: admin
  
- url: /welcome-back
  script: welcome_back.app
  login: admin

libraries:
- name: webapp2
  version: "2.5.1"
- name: django
  version: "1.4"
- name: ssl
  version: "latest"
  