application: nozomi-miraha
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /hello
  script: helloworld.app
  login: admin

- url: /good-night
  script: good_night.app
  login: admin
